// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kahnxnzjftqijavjqias.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthaG54bnpqZnRxaWphdmpxaWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjAzMjMsImV4cCI6MjA2MjczNjMyM30.sWUyW-hovO28JZvzlMei9S513HEx9-PJyKzLpfbskuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);